### ISSUE TITLE
ErrorCode 3 - RequestOAuthError: Authentication error

### ISSUE THREAD

**Issue by boriswerner** [mrbungle64/ecovacs-deebot.js#37] opened 2020-05-09 11:20 UTC
ErrorCode 3 - RequestOAuthError: Authentication error
is occuring sometimes during normal operation. It seems to be related to several instances of the library (e.g. different machines or same machine, different devices) running at the same time.

This issue is to track the occurences and describe them as detailed as possible
- when was/were the instance/s started?
- when did the error occur?
- what else could be relevant?

**Comment by boriswerner** [comment] 2020-05-09 11:22
09.05.2020
11:30 Stopped instance on RPi
11:35:07 - 11:44:55 testing with VSCode and second iobroker installation (Windwos) , then stopped both
11:55:25 started instance on RPi
12:52:25 state change info.error => RequestOAuthError: Authentication error
Instance Reboot 13:04:09 --> ok

**Comment by mrbungle64** [comment] 2020-05-09 11:26
Deebot 901 / ioBroker Adapter:
```
2020-05-09 13:07:01.278 | terminating
2020-05-09 13:07:01.277 | cleaned everything up...
...
2020-05-09 12:53:03.340 | cleaned everything up...
```

**Comment by mrbungle64** [comment] 2020-11-16 21:37
This is hopefully fixed now.

Please use `getDeviceId()` for getting a unique device id and a device number if running multiple devices.

```javascript
const deviceNumber = 0;
const deviceId = EcoVacsAPI.getDeviceId(nodeMachineId.machineIdSync(), deviceNumber)
```

**Comment by mrbungle64** [comment] 2020-11-27 13:03
@bwp91 @nicoduj @bertreb

Starting with [version 0.5.0](https://www.npmjs.com/package/ecovacs-deebot/v/0.5.0) you can run multiple devices at once without having this issue.
You must use the `getDeviceId()` method mentioned above and pass a unique device number (or name) in addition to the machineId.

cc: @boriswerner

**Comment by mrbungle64** [comment] 2020-11-27 16:38
> @bwp91 @nicoduj @bertreb
> 
> Starting with [version 0.5.0](https://www.npmjs.com/package/ecovacs-deebot/v/0.5.0) you can run multiple devices at once without having this issue.
> You must use the `getDeviceId()` method mentioned above and pass a unique device number (or name) in addition to the machineId.
> 
> cc: @boriswerner

@bwp91 @nicoduj

Unfortunately the Ecovacs API seems to require the `deviceId` to login.
I tried to detach the device instance from the login, but so far I did not succeed.

If I get it right HomeBridge doesn't allow multiple instances for a plugin anymore so maybe this is not an instant solution for you...

**Comment by mrbungle64** [comment] 2020-11-27 19:00
> Unfortunately the Ecovacs API seems to require the deviceId to login.
> I tried to detach the device instance from the login, but so far I did not succeed.

Maybe I'm wrong, because I suspect now that they mean the `deviceId` of the mobile device the app is running on.

```js
    this.meta = {
      'country': country,
      'lang': 'en',
      'deviceId': device_id,
      'appCode': 'i_eco_e',
      'appVersion': '1.3.5',
      'channel': 'c_googleplay',
      'deviceType': '1'
    };
```

**Comment by nicoduj** [comment] 2020-11-28 10:33
Hi, might be the case for deviceId, maybe they use it for notifications . Let me know if I can help in any way, will integrate your changes afterwards

**Comment by mrbungle64** [comment] 2020-11-28 12:43
The problem is that this `deviceId` is also used for authorization when sending a command like `Clean` or `GetWaterLevel`.
In this case it's used for the `resource`, and `this.resource` is equal to the `deviceId` that is used during the login process.

```js
   const auth = {
       'realm': constants.REALM,
       'resource': this.resource,
       'token': this.secret,
       'userid': this.user,
       'with': 'users',
   }
```

My tests running 2 devices of different models running simultaneously if using the same `deviceId`:

|Model|Slim 2 (XMPP)|Ozmo 930 (XMPP)|Deebot 901 (MQTT/XML)|Ozmo 920 (MQTT/JSON)|
| :- | :-: | :-: | :-: | :-: |
|**Slim 2 (XMPP)**|/|works|works partially *|works partially *|
|**Ozmo 930 (XMPP)**|works|/|works partially *|works partially *|
|**Deebot 901 (MQTT/XML)**|works partially *|works partially *|/|doesn't work|
|**Ozmo 920 (MQTT/JSON)**|works partially *|works partially *|doesn't work|/|

*) Works if the XMPP based device is already successfully connected

**Comment by nicoduj** [comment] 2020-11-28 13:03
Myabe we are talking about 2 differents things ? Resource -> deviceId -> the unique identifier of the device for post commands, , and deviceId in the login function that is the mobile phone ?  Do you get any resource id on each vaccum after login ?

**Comment by mrbungle64** [comment] 2020-11-28 13:30
@nicoduj 

> (did not look deeper into api, so maybe what I am saying is dumb, sorry if it is the case)

No, it's not "dumb" ... I think you are right when it comes to what we would expect, how it works :)

But the `deviceId` that is used for login (mobile app and ecovacs-deebot library) is equal to the `resource` that is used for sending post requests.

> Do you get any resource id on each vaccum after login ?

Yes, but it seams that you cannot use it for authorization in the case of sending the post requests.

For each vacuum we get:
* `did` (which maybe means "device id")
* `name` (which starts with "E0" and in the case of the XMPP devices it seams to be equal with the `did`)
* `resource` (a string like 'atom' in the case of the XMPP or for example "36OA" in the case of Ozmo 920)

**Comment by nicoduj** [comment] 2020-11-28 13:41
okay, so maybe they are expecting some kind of string concat there Did you run the app with some reverse proxy to see the post bidy from the app ? (like charles) ?

**Comment by mrbungle64** [comment] 2020-11-28 13:53
> Did you run the app with some reverse proxy to see the post bidy from the app ? (like charles) ?

Not yet

**Comment by mrbungle64** [comment] 2020-11-28 14:09
The library actually performs proper authorization. However, to run multiple MQTT-based devices, you need a separate login procedure for each device, each with a unique device id.

With the mobile app you cannot control multiple devices at once. You have to choose one device first before you're able to send commands.

In the [ioBroker adapter](https://github.com/mrbungle64/ioBroker.ecovacs-deebot) and the [Node-Red node](https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot) you have seperate instances for each device. So if you use a unique device id for each device it's working fine now.

**Comment by nicoduj** [comment] 2020-11-28 15:19
Ok, seems indeed plausible . will think of it, but it seems that there would be not way to support this without 2 homebridge instances

**Closed** 2021-02-21 16:53 UTC
Labels: Verification, Wontfix
