### ISSUE TITLE
Features report wrong for OZMO slim 10 with latest beta

### ISSUE THREAD

**Issue by nicoduj** [mrbungle64/ecovacs-deebot.js#75] opened 2021-04-20 09:31 UTC
Hi,

I got I think wrong feature report for OZMO slim 10 with latest beta 

[2021-4-20 11:28:40] [DeebotEcovacs] INFO - Edge Cleaning for Alfred : false
[2021-4-20 11:28:40] [DeebotEcovacs] INFO - Spot Cleaning for Alfred : false
[2021-4-20 11:28:40] [DeebotEcovacs] INFO - SpotArea Cleaning for Alfred : true
[2021-4-20 11:28:40] [DeebotEcovacs] INFO - CustomArea Cleaning for Alfred : false

instead of

[4/20/2021, 10:14:46 AM] [homebridge-deebotecovacs] INFO - Edge Cleaning for Alfred : true
[4/20/2021, 10:14:46 AM] [homebridge-deebotecovacs] INFO - Spot Cleaning for Alfred : true
[4/20/2021, 10:14:46 AM] [homebridge-deebotecovacs] INFO - SpotArea Cleaning for Alfred : false
[4/20/2021, 10:14:46 AM] [homebridge-deebotecovacs] INFO - CustomArea Cleaning for Alfred : false

**Comment by mrbungle64** [comment] 2021-04-20 10:39
Hi @nicoduj 

I [added the config](https://github.com/mrbungle64/ecovacs-deebot.js/commit/086b37b883b063f8e6a822c1c09aeccbd0b23e19) for OZMO Slim 10 based on the following informations: https://github.com/mrbungle64/ecovacs-deebot.js/issues/69#issuecomment-810567436

Can you confirm that the OZMO Slim 10 supports Spot Area cleaning?
The problem is here, that usally devices with Spot Area and Custom Area cleaning don't support Edge and Spot cleaning.

**Comment by nicoduj** [comment] 2021-04-20 10:44
Hi, from the deebot app mine has : edge, auto, and spot (Spécifique in french)  (1X1, 2x2, 3x2).

**Comment by mrbungle64** [comment] 2021-04-20 10:49
> Hi, from the deebot app mine has : edge, auto, and spot (Spécifique in french) (1X1, 2x2, 3x2). Previous report seemed better to me (no area at all on this model I think)

ok, I'll change it to `"spot_area": false`.
This automatically changes the other two values back to `true`.

**Comment by mrbungle64** [comment] 2021-04-22 18:10
@nicoduj 
Should be fixed with version 0.6.0

**Closed** 2021-04-24 12:22 UTC
Labels: Bug
